/*
 * AddXNATServer.java
 *
 * Created on May 28, 2010, 1:32:49 PM
 */

package org.nrg.xnat.gui;

/**
 *
 * @author Aditya Siram
 */
public class AddXNATServer extends javax.swing.JFrame {
    private ChildManager c;
    private UpdateServerTable t;

    /** Creates new form AddXNATServer */
    public AddXNATServer(ChildManager c, UpdateServerTable t) {
        this.t = t;
        initComponents();
        this.c = c;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        error_dialog = new javax.swing.JDialog();
        server_properties_title = new javax.swing.JLabel();
        cancel_button = new javax.swing.JButton();
        password_label = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        username_label = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        url_label = new javax.swing.JLabel();
        url_textfield = new javax.swing.JTextField();
        server_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        password_textfield = new javax.swing.JTextField();

        error_dialog.setTitle("Add error");
        error_dialog.setAlwaysOnTop(true);

        javax.swing.GroupLayout error_dialogLayout = new javax.swing.GroupLayout(error_dialog.getContentPane());
        error_dialog.getContentPane().setLayout(error_dialogLayout);
        error_dialogLayout.setHorizontalGroup(
            error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        error_dialogLayout.setVerticalGroup(
            error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        server_properties_title.setText("Add XNAT Server");

        cancel_button.setText("Cancel");
        cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancel_buttonMousePressed(evt);
            }
        });

        password_label.setText("Password");

        add_button.setText("Add");
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_buttonMousePressed(evt);
            }
        });

        username_label.setText("Username");

        username_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textfieldActionPerformed(evt);
            }
        });

        url_label.setText("URL");

        url_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                url_textfieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(url_label)
                            .addComponent(username_label)
                            .addComponent(password_label)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(server_properties_title)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(password_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(url_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(server_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(server_properties_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(server_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(url_label)
                    .addComponent(url_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button)
                    .addComponent(cancel_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textfieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_username_textfieldActionPerformed

    private void url_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_url_textfieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_url_textfieldActionPerformed

    private void cancel_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMousePressed
        this.dispose();
    }//GEN-LAST:event_cancel_buttonMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.c.remove_from_child_count();
    }//GEN-LAST:event_formWindowClosed

    private void add_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMousePressed
        if (t.add_server(server_name.getText(), url_textfield.getText(), username_textfield.getText(), password_textfield.getText())) {
            this.dispose();
        }
    }//GEN-LAST:event_add_buttonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JDialog error_dialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField password_textfield;
    private javax.swing.JTextField server_name;
    private javax.swing.JLabel server_properties_title;
    private javax.swing.JLabel url_label;
    private javax.swing.JTextField url_textfield;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
