/*
 * InitialSetupGUI.java
 *
 * Created on Jun 4, 2010, 4:07:49 PM
 */

package org.nrg.xnat.gui;

import java.io.File;
import java.io.IOException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import org.nrg.xnat.env.AuthenticatedDevice;
import org.nrg.xnat.env.util.EncryptionUtils;
import org.nrg.xnat.util.Utils;

/**
 *
 * @author Aditya Siram
 */
public class InitialSetupGUI extends javax.swing.JFrame {
    private String error;
    private Properties p;
    private InitialProperties controller;

    /** Creates new form InitialSetupGUI */
    public InitialSetupGUI(InitialProperties controller) {
        this.controller = controller;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        initial_ae_title = new javax.swing.JTextField();
        initial_listening_port = new javax.swing.JTextField();
        initial_xnat_name = new javax.swing.JTextField();
        initial_xnat_hostname = new javax.swing.JTextField();
        initial_xnat_username = new javax.swing.JTextField();
        initial_apply_button = new javax.swing.JButton();
        initial_cancel_button = new javax.swing.JButton();
        initial_xnat_password = new javax.swing.JPasswordField();
        allowAnonymousAE_check_box = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Initial Setup");

        jLabel2.setText("Gateway Settings");

        jLabel3.setText("AE Title");

        jLabel4.setText("Port");

        jLabel5.setText("Default XNAT Server");

        jLabel6.setText("Name");

        jLabel7.setText("Hostname");

        jLabel8.setText("Username");

        jLabel9.setText("Password");

        initial_apply_button.setText("Apply");
        initial_apply_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                initial_apply_buttonMousePressed(evt);
            }
        });

        initial_cancel_button.setText("Cancel");
        initial_cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                initial_cancel_buttonMousePressed(evt);
            }
        });

        initial_xnat_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initial_xnat_passwordActionPerformed(evt);
            }
        });

        allowAnonymousAE_check_box.setText(" Allow Retrieve From Anonymous Remote AEs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(initial_listening_port)
                                    .addComponent(initial_ae_title, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(initial_xnat_name)
                                    .addComponent(initial_xnat_hostname, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(initial_xnat_password, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(initial_xnat_username)))
                            .addComponent(allowAnonymousAE_check_box)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(initial_apply_button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(initial_cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initial_ae_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(initial_listening_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(allowAnonymousAE_check_box)
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(initial_xnat_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(initial_xnat_hostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(initial_xnat_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(initial_xnat_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initial_apply_button)
                    .addComponent(initial_cancel_button))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-399)/2, (screenSize.height-475)/2, 399, 475);
    }// </editor-fold>//GEN-END:initComponents

    private void initial_apply_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initial_apply_buttonMousePressed
        if (!ensure_all_there()) {
            GUIUtils.warn("The following errors were found: \n" + error, "Add error");
            error = null;
        } else {
            try {
                this.p = fill_in_properties();
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(InitialSetupGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(InitialSetupGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchPaddingException ex) {
                Logger.getLogger(InitialSetupGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidKeyException ex) {
                Logger.getLogger(InitialSetupGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidAlgorithmParameterException ex) {
                Logger.getLogger(InitialSetupGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalBlockSizeException ex) {
                Logger.getLogger(InitialSetupGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BadPaddingException ex) {
                Logger.getLogger(InitialSetupGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                controller.initialSetupDone(p);
                this.dispose();
            } catch (IOException ex) {
                GUIUtils.warn(ex.toString(), "Setup error");
                System.exit(1);
            }
        }
    }//GEN-LAST:event_initial_apply_buttonMousePressed

    private void initial_cancel_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initial_cancel_buttonMousePressed
        quit();
    }//GEN-LAST:event_initial_cancel_buttonMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        quit();
    }//GEN-LAST:event_formWindowClosing

    private void initial_xnat_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initial_xnat_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initial_xnat_passwordActionPerformed

    private void quit() {
        int quit_confirm = JOptionPane.showConfirmDialog(null,
                                                       "The server cannot run without this information.\n Are you sure you want to quit?",
                                                       "Setup error",
                                                       JOptionPane.YES_NO_OPTION,
                                                       JOptionPane.WARNING_MESSAGE);
        if (quit_confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private Properties fill_in_properties() throws NoSuchAlgorithmException, IOException, NoSuchPaddingException, InvalidKeyException, InvalidAlgorithmParameterException, IllegalBlockSizeException, BadPaddingException {
        Properties _p = new Properties ();
        _p.setProperty("Dicom.CalledAETitle", initial_ae_title.getText());
        _p.setProperty("Dicom.CallingAETitle", initial_ae_title.getText());
        _p.setProperty("Dicom.ListeningPort", initial_listening_port.getText());
        _p.setProperty("XNATServers." + initial_xnat_name.getText() + ".User", initial_xnat_username.getText());
        EncryptionUtils.createKeyFile(new File(AuthenticatedDevice.keyFile));
        _p.setProperty("XNATServers." + initial_xnat_name.getText() + ".Pass", 
                       EncryptionUtils.encrypt(new String(initial_xnat_password.getPassword()), new File(AuthenticatedDevice.keyFile)));
        _p.setProperty("XNATServers." + initial_xnat_name.getText() + ".ServerURL", initial_xnat_hostname.getText());
        _p.setProperty("XNATServers.default", initial_xnat_name.getText());
        _p.setProperty("XNATServers", initial_xnat_name.getText());
        _p.setProperty("Dicom.AnonymousAEAllowed", Boolean.toString(allowAnonymousAE_check_box.isSelected()));
        return _p;
    }

    private boolean ensure_all_there () {
        error = "";
        if (!Utils.has_content(initial_ae_title.getText())) {
            error += "No AE title for the gateway. \n";
        }
        if (!Utils.has_content(initial_listening_port.getText()) ||
                   !Utils.is_a_number(initial_listening_port.getText())) {
            error += "No listening port for the gateway. \n";
        } 
        if (!Utils.has_content(initial_xnat_name.getText())) {
            error += "No default XNAT server name.\n";
        } 
        if (!Utils.has_content(initial_xnat_hostname.getText())) {
            error += "No default XNAT server hostname.\n";
        }
        if (!Utils.has_content(initial_xnat_username.getText())) {
            error += "No default XNAT server username. \n";
        }
        if (!Utils.has_content(initial_xnat_password.getText())) {
            error += "No default XNAT server password. \n";
        }
        if (Utils.has_content(error)) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allowAnonymousAE_check_box;
    private javax.swing.JTextField initial_ae_title;
    private javax.swing.JButton initial_apply_button;
    private javax.swing.JButton initial_cancel_button;
    private javax.swing.JTextField initial_listening_port;
    private javax.swing.JTextField initial_xnat_hostname;
    private javax.swing.JTextField initial_xnat_name;
    private javax.swing.JPasswordField initial_xnat_password;
    private javax.swing.JTextField initial_xnat_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
